/// <reference types="@cloudflare/workers-types" />

// OpenNext generates this module before Wrangler bundles the custom entrypoint.
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore generated by `opennextjs-cloudflare build`
import handler from "./.open-next/worker.js";
import { DurableObject } from "cloudflare:workers";
import { BoardMeetingRoomHandler } from "./lib/server/board-meeting-room";

const worker = {
  fetch: handler.fetch,
};
export default worker;

export class BoardMeetingRoom extends DurableObject<CloudflareEnv> {
  private readonly room: BoardMeetingRoomHandler;

  constructor(ctx: DurableObjectState, env: CloudflareEnv) {
    super(ctx, env);
    this.room = new BoardMeetingRoomHandler(ctx);
  }

  fetch(request: Request): Promise<Response> {
    return this.room.fetch(request);
  }

  alarm(): Promise<void> {
    return this.room.alarm();
  }
}

// Preserve OpenNext's optional Durable Object exports.
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore generated by `opennextjs-cloudflare build`
export { DOQueueHandler, DOShardedTagCache, BucketCachePurge } from "./.open-next/worker.js";
