/**
 * Generates the voiceover from audio/script.json with ElevenLabs.
 *
 *   ELEVENLABS_API_KEY=... node scripts/gen-vo.mjs [--voice <id>] [--tag <name>]
 *
 * The whole script is read in ONE take. Splitting it into ten requests makes
 * every line restart at "first sentence" intonation, which is most of what makes
 * a synthetic read sound synthetic; in one pass the model carries breath and
 * emphasis across the sentence boundaries the way a person does.
 *
 * The take comes back with character-level timings. Those are used to cut it
 * back apart at the line boundaries — each clip keeps the delivery it was read
 * with, but the film gets to choose how much air sits between the lines
 * (`src/timeline.ts`), which one continuous file would not allow: ElevenLabs
 * leaves about a tenth of a second between sentences, and a launch film needs
 * more than that.
 *
 * `--tag <name>` writes an audition take to public/audio/auditions/ and changes
 * nothing else, so a different voice can be compared without retiming the film.
 */
import { mkdir, writeFile, readFile, rm } from "node:fs/promises";
import { execFile } from "node:child_process";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { promisify } from "node:util";

const run = promisify(execFile);
const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(HERE, "..");

const KEY = process.env.ELEVENLABS_API_KEY;
if (!KEY) throw new Error("ELEVENLABS_API_KEY is not set");

const args = process.argv.slice(2);
const flag = (name) => {
  const i = args.indexOf(`--${name}`);
  return i === -1 ? undefined : args[i + 1];
};

const script = JSON.parse(await readFile(resolve(ROOT, "audio/script.json"), "utf8"));
const voice = flag("voice") ?? script.voice;
const tag = flag("tag");

/** Line boundaries in the joined text, so timings can be attributed back. */
const spans = [];
let text = "";
for (const line of script.lines) {
  if (text) text += " ";
  spans.push({ id: line.id, from: text.length, to: text.length + line.text.length });
  text += line.text;
}

const res = await fetch(
  `https://api.elevenlabs.io/v1/text-to-speech/${voice}/with-timestamps?output_format=mp3_44100_192`,
  {
    method: "POST",
    headers: { "xi-api-key": KEY, "content-type": "application/json" },
    body: JSON.stringify({
      text,
      model_id: script.model,
      voice_settings: {
        // Low stability is what keeps v3 sounding like a person rather than a
        // reader; the style push adds the small hesitations and emphasis shifts
        // someone actually uses when they mean what they are saying.
        stability: 0.35,
        similarity_boost: 0.75,
        style: 0.45,
        use_speaker_boost: true,
      },
    }),
  },
);
if (!res.ok) throw new Error(`${res.status} ${await res.text()}`);

const body = await res.json();
const align = body.alignment ?? body.normalized_alignment;
if (!align) throw new Error("no alignment returned");

const starts = align.character_start_times_seconds;
const ends = align.character_end_times_seconds;
const marks = spans.map(({ id, from, to }) => ({
  id,
  start: starts[Math.min(from, starts.length - 1)],
  end: ends[Math.min(to - 1, ends.length - 1)],
}));
const total = ends[ends.length - 1];

console.log(`voice ${voice} · ${total.toFixed(2)}s`);

if (tag) {
  const dir = resolve(ROOT, "audio/auditions");
  await mkdir(dir, { recursive: true });
  await writeFile(resolve(dir, `${tag}.mp3`), Buffer.from(body.audio_base64, "base64"));
  console.log(`wrote audio/auditions/${tag}.mp3 (audition only — film not retimed)`);
  process.exit(0);
}

const takeDir = resolve(ROOT, "audio");
await mkdir(takeDir, { recursive: true });
const take = resolve(takeDir, "take.mp3");
await writeFile(take, Buffer.from(body.audio_base64, "base64"));

// Cut on the midpoint of each gap, so every clip keeps its own breath in and out.
const outDir = resolve(ROOT, "public/audio/vo");
await rm(outDir, { recursive: true, force: true });
await mkdir(outDir, { recursive: true });

const clips = [];
for (const [i, m] of marks.entries()) {
  const prev = marks[i - 1];
  const next = marks[i + 1];
  const from = prev ? (prev.end + m.start) / 2 : Math.max(0, m.start - 0.12);
  const to = next ? (m.end + next.start) / 2 : Math.min(total, m.end + 0.2);
  await run("ffmpeg", [
    "-hide_banner", "-loglevel", "error", "-y",
    "-i", take,
    "-ss", from.toFixed(3), "-to", to.toFixed(3),
    "-c:a", "libmp3lame", "-b:a", "192k",
    resolve(outDir, `${m.id}.mp3`),
  ]);
  clips.push({ id: m.id, duration: to - from });
  console.log(`  ${m.id.padEnd(10)} ${(to - from).toFixed(2)}s`);
}

const ts = `/**
 * Voiceover clips, generated by \`scripts/gen-vo.mjs\` — do not hand-edit.
 *
 * One file per line of \`audio/script.json\`, cut out of a single continuous
 * ElevenLabs take. Durations are seconds. The gaps between them are the film's
 * to choose: see \`src/timeline.ts\`.
 */
export const VO_CLIPS = [
${clips.map((c) => `  { id: "${c.id}", duration: ${c.duration.toFixed(3)} },`).join("\n")}
] as const;

export type VoLine = (typeof VO_CLIPS)[number]["id"];
`;
await writeFile(resolve(ROOT, "src/vo.ts"), ts);
console.log("wrote src/vo.ts");
