/**
 * Voiceover clips, generated by `scripts/gen-vo.mjs` — do not hand-edit.
 *
 * One file per line of `audio/script.json`, cut out of a single continuous
 * ElevenLabs take. Durations are seconds. The gaps between them are the film's
 * to choose: see `src/timeline.ts`.
 */
export const VO_CLIPS = [
  { id: "01-hook", duration: 3.386 },
  { id: "02-setup", duration: 5.078 },
  { id: "03-brief", duration: 3.120 },
  { id: "04-form", duration: 4.312 },
  { id: "05-argue", duration: 3.376 },
  { id: "06-tools", duration: 4.222 },
  { id: "07-mcp", duration: 5.067 },
  { id: "08-agent", duration: 4.568 },
  { id: "09-memo", duration: 4.932 },
  { id: "10-end", duration: 2.580 },
] as const;

export type VoLine = (typeof VO_CLIPS)[number]["id"];
